services:
  gs-agent:
    build:
      context: .
      args:
        VERSION: 0.0.2
    image: gs-agent-bot:0.0.2
    container_name: gs_agent
    restart: unless-stopped
    volumes:
      - ./gs_db:/gs_agent/gs_db
      - ./logs:/gs_agent/logs
      - ./fastembed_cache:/tmp/fastembed_cache
    env_file:
      - .env